### ISSUE TITLE
【HELP】Some problems in Debug！？？

### ISSUE THREAD

**Issue by wuwusky** [researchmm/DBTNet#4]
hi，Thanks for your share！
but, when I dubug the module GroupConv(nn.Conv2D) like this code, I get this error output: 'symbol' object has no attribute 'diag'. May u tell me, how I can use this module Independently？
`
temp_model = GroupConv(2048, kernel_size=1, use_bias=False, width=224)

temp_model.initialize(mx.init.MSRAPrelu())

temp_input = nd.random.normal(-1, 1, shape=(2,3, 224, 224))

temp_output = temp_model(temp_input)
` 
I am an newer for MXNET

**Comment by wuwusky** [comment]
Another question is that, the usage of the 'super' in the hybrid_forward() of the class 'GroupConv' is for computing the GroupConv(hybrid_forward) twice or just want to use the class 'nn.Conv2D' for once?
@wkcn @Sy-Zhang @HYPJUDY @Jianlong-Fu @Heliang-Zheng
After a test, the problem has been sovled~, the super is used for to forward by the class 'nn.Conv2D' once~, thanks for your code!

**Comment by wkcn** [comment]
Hi @wuwusky ,
The first question:
Which version of MXNet do you use? 
The method `.diag()` may not exists in the old version of MXNet.
I recommend to use the latest version, MXNet 1.6 : )

The second question:
https://github.com/researchmm/DBTNet/blob/40877de074e10f84749a5f5acda0594d5c1172e0/dbt.py#L210

`GroupConv` is inherited from `nn.Conv2D`, and `super(GroupConv, self).hybrid_forward` means calling the forward function of a basic convolution.

**Comment by wuwusky** [comment]
> Hi @wuwusky ,
> The first question:
> Which version of MXNet do you use?
> The method `.diag()` may not exists in the old version of MXNet.
> I recommend to use the latest version, MXNet 1.6 : )
> 
> The second question:
> https://github.com/researchmm/DBTNet/blob/40877de074e10f84749a5f5acda0594d5c1172e0/dbt.py#L210
> 
> `GroupConv` is inherited from `nn.Conv2D`, and `super(GroupConv, self).hybrid_forward` means calling the forward function of a basic convolution.

Thanks very much~ i ignored the version of MXNET！
