### ISSUE TITLE
About the use of position encoding between the convolutional channel

### ISSUE THREAD

**Issue by SWHL** [researchmm/DBTNet#6]
- Thank you for your work.
- I am very interested with your work, but confused with the position encoding in the convolutional channels. 
- In the https://github.com/researchmm/DBTNet/blob/40877de074e10f84749a5f5acda0594d5c1172e0/dbt.py#L101 **I can't find out where to use the `self.bias` and the `self.weight`**.
- I am looking forward to your answer.

**Comment by SWHL** [comment]
According to the author, I guess it should be used here:
https://github.com/researchmm/DBTNet/blob/40877de074e10f84749a5f5acda0594d5c1172e0/dbt.py#L117
I guess the right code may be this:
```python
mytmp = F.FullyConnected(tmp, num_hidden=128,weight = self.weight, bias=self.bias)
```

**Comment by Heliang-Zheng** [comment]
@SWHL 
I followed this introduction to custom the ner layer:
https://mxnet.apache.org/api/python/docs/tutorials/extend/custom_layer.html#Parameters-of-a-custom-layer
the bias and weights can be used without 'self.'
Thanks for your interests!
