### ISSUE TITLE
The structure of DBTNet-50 does not correspond in the paper and the source code.

### ISSUE THREAD

**Issue by SWHL** [researchmm/DBTNet#7]
- Thanks you for your work.
- The structure of DBTNet-50 in the **paper**:
![Snipaste_2019-12-24_08-07-46](https://user-images.githubusercontent.com/28639377/71385928-3a2e9c00-2625-11ea-8f6c-d2765bc65db1.png)

- The structure in the **source code**:
https://github.com/researchmm/DBTNet/blob/40877de074e10f84749a5f5acda0594d5c1172e0/dbt.py#L442

The souce code shows that when `stage_index == 3` or `stage_index == 4`, in other words, the `Block3` or `Block4`  two blocks only have **SG(Semantic Grouping Layer)** and **GB(Group Bilinear Layer)** modules. 
- But this is different from the structure described in the origin paper.
- I hope the authors can help me to answer the confusion.
- Thank you very much again.

**Comment by wuwusky** [comment]
> * Thanks you for your work.
> * The structure of DBTNet-50 in the **paper**:
>   ![Snipaste_2019-12-24_08-07-46](https://user-images.githubusercontent.com/28639377/71385928-3a2e9c00-2625-11ea-8f6c-d2765bc65db1.png)
> * The structure in the **source code**:
>   https://github.com/researchmm/DBTNet/blob/40877de074e10f84749a5f5acda0594d5c1172e0/dbt.py#L442
> 
> The souce code shows that when `stage_index == 3` or `stage_index == 4`, in other words, the `Block3` or `Block4` two blocks only have **SG(Semantic Grouping Layer)** and **GB(Group Bilinear Layer)** modules.
> 
> * But this is different from the structure described in the origin paper.
> * I hope the authors can help me to answer the confusion.
> * Thank you very much again.


aha~you can scan **section** **4.2 Ablation studies** of the paper, **Table 5: Ablation study on itergrated stages**
![image](https://user-images.githubusercontent.com/34291546/71400443-c363c400-2661-11ea-9162-5bec11dfa5fe.png)

**Comment by SWHL** [comment]
- Thanks
- I missed the detail -_-!
