### ISSUE TITLE
About the shape of tmp in the GB2HybridLayer

### ISSUE THREAD

**Issue by SWHL** [researchmm/DBTNet#9]
- I wonder why the tmp is reshaped to `(-1, 128)`,  why is it `128`?
- I think it should usually be `2048`.

**Comment by Heliang-Zheng** [comment]
@SWHL
Yes, I think you are right. I made this mistake when I cleaned the code, since GB2HybridLayer was originally designed for the Second Stage, whose channel number is 128.
